#!/usr/bin/env python2.7
# usage: 
# scp-m -r folder/subfolder marcc/scratch/folder

import subprocess
import binascii
import sys
import pexpect

PIN="5QPNNKSFLU3PCBCL"
PASS='yaseichasdoma'
USER="guritsk1@jhu.edu"


source = sys.argv[-2]
destination = sys.argv[-1]

if source[0:5]=="marcc": source=USER+"@gateway2.marcc.jhu.edu:/home-2/"+USER + source[5:]
if destination[0:5]=="marcc": destination=USER+"@gateway2.marcc.jhu.edu:/home-2/"+USER + destination[5:]

#if sys.argv[-3]!="-r": command = "scp "+source+' '+destination
command = "scp -r "+source+' '+destination
print command

child = pexpect.spawn(command)
child.expect('Verification code: '.decode('unicode-escape'))
code = subprocess.Popen(["oathtool", "--totp", "-b", " "+PIN],stdout=subprocess.PIPE).stdout.readline().rstrip('\n')
child.sendline(code)

child.expect('Password: '.decode('unicode-escape'))
child.sendline(PASS)

sys.stdout.write (child.after)
sys.stdout.flush()
child.interact()
